### ISSUE TITLE
section-about item fix

### ISSUE THREAD

**Issue by sekerhalithamza** [furkanesenn/furkanesenn.github.io#2]
![image](https://github.com/furkanesenn/furkanesenn.github.io/assets/104067464/78732cc9-2b6e-49c5-8aae-a2c40d09eafe)

**Comment by furkanesenn** [comment]
Thank you for opening an issue on my repository. I appreciate your input and I'll make sure to address it.

**Comment by furkanesenn** [comment]
Done.
